package com.upc.industry.dataobject;

import java.util.Date;

public class SysErrorDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error.id
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error.user_name
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error.class_name
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error.method_name
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error.exception_type
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    private String exceptionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error.ip
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error.operate_date
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    private Date operateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_error.exception_msg
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    private String exceptionMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error.id
     *
     * @return the value of sys_error.id
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error.id
     *
     * @param id the value for sys_error.id
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error.user_name
     *
     * @return the value of sys_error.user_name
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error.user_name
     *
     * @param userName the value for sys_error.user_name
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error.class_name
     *
     * @return the value of sys_error.class_name
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error.class_name
     *
     * @param className the value for sys_error.class_name
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error.method_name
     *
     * @return the value of sys_error.method_name
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error.method_name
     *
     * @param methodName the value for sys_error.method_name
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error.exception_type
     *
     * @return the value of sys_error.exception_type
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public String getExceptionType() {
        return exceptionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error.exception_type
     *
     * @param exceptionType the value for sys_error.exception_type
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public void setExceptionType(String exceptionType) {
        this.exceptionType = exceptionType == null ? null : exceptionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error.ip
     *
     * @return the value of sys_error.ip
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error.ip
     *
     * @param ip the value for sys_error.ip
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error.operate_date
     *
     * @return the value of sys_error.operate_date
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public Date getOperateDate() {
        return operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error.operate_date
     *
     * @param operateDate the value for sys_error.operate_date
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public void setOperateDate(Date operateDate) {
        this.operateDate = operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_error.exception_msg
     *
     * @return the value of sys_error.exception_msg
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public String getExceptionMsg() {
        return exceptionMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_error.exception_msg
     *
     * @param exceptionMsg the value for sys_error.exception_msg
     *
     * @mbg.generated Tue Jul 21 15:07:24 CST 2020
     */
    public void setExceptionMsg(String exceptionMsg) {
        this.exceptionMsg = exceptionMsg == null ? null : exceptionMsg.trim();
    }
}