package com.upc.industry.dataobject;

public class UserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_infor.id
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_infor.name
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_infor.gender
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_infor.telphone
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_infor.age
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infor.id
     *
     * @return the value of user_infor.id
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infor.id
     *
     * @param id the value for user_infor.id
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infor.name
     *
     * @return the value of user_infor.name
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infor.name
     *
     * @param name the value for user_infor.name
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infor.gender
     *
     * @return the value of user_infor.gender
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infor.gender
     *
     * @param gender the value for user_infor.gender
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infor.telphone
     *
     * @return the value of user_infor.telphone
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infor.telphone
     *
     * @param telphone the value for user_infor.telphone
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infor.age
     *
     * @return the value of user_infor.age
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infor.age
     *
     * @param age the value for user_infor.age
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}