package com.upc.industry.dao;

import com.upc.industry.dataobject.UserDO;
import org.apache.ibatis.annotations.Param;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    UserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Mon Jul 20 17:27:33 CST 2020
     */
    int updateByPrimaryKey(UserDO record);
    int countByPhone(@Param("phone") String phone, @Param("id") Integer id);
}